/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JCheckBox;


/**
 *
 * @author rules
 */
public class FormPendaftaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPendaftaran.class.getName());

    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
        setLocationRelativeTo(null);
        NamaField.putClientProperty("JTextField.placeholderText", "Nama lengkap");
NpmField.putClientProperty("JTextField.placeholderText", "Contoh: 2410010001");
getRootPane().setDefaultButton(DaftarBt);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NamaField = new javax.swing.JTextField();
        NpmField = new javax.swing.JTextField();
        ProgramBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DarkBt = new javax.swing.JButton();
        DaftarBt = new javax.swing.JButton();
        LakiRb = new javax.swing.JRadioButton();
        JavaCb = new javax.swing.JCheckBox();
        PyCb = new javax.swing.JCheckBox();
        WebCb = new javax.swing.JCheckBox();
        CeweRb = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form pendaftaran workshop");

        jLabel2.setText("NAMA");

        jLabel3.setText("NPM");

        jLabel4.setText("Program Studi");

        NamaField.addActionListener(this::NamaFieldActionPerformed);

        ProgramBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Manajemen Informatika", " " }));
        ProgramBox.addActionListener(this::ProgramBoxActionPerformed);

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Minat");

        DarkBt.setText("Dark Mode");
        DarkBt.addActionListener(this::DarkBtActionPerformed);

        DaftarBt.setText("Daftar");
        DaftarBt.addActionListener(this::DaftarBtActionPerformed);

        Kelamin.add(LakiRb);
        LakiRb.setText("Laki-Laki");
        LakiRb.addActionListener(this::LakiRbActionPerformed);

        JavaCb.setText("Java");

        PyCb.setText("Python");

        WebCb.setText("Web");

        Kelamin.add(CeweRb);
        CeweRb.setText("Perempuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DarkBt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DaftarBt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NpmField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NamaField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProgramBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LakiRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CeweRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JavaCb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PyCb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(WebCb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(NpmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ProgramBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LakiRb)
                    .addComponent(CeweRb))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JavaCb)
                    .addComponent(PyCb)
                    .addComponent(WebCb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DarkBt)
                    .addComponent(DaftarBt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaFieldActionPerformed

    private void ProgramBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramBoxActionPerformed

    private void LakiRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LakiRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LakiRbActionPerformed

    private void DaftarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarBtActionPerformed
        // TODO add your handling code here:
        tampilkanRingkasan();
    }//GEN-LAST:event_DaftarBtActionPerformed

    private void DarkBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarkBtActionPerformed
        // TODO add your handling code here
        
isDarkMode = !isDarkMode; 
        gantiTema(isDarkMode);



    }//GEN-LAST:event_DarkBtActionPerformed
private boolean isDarkMode = false;
    private void tampilkanRingkasan() {
String jenisKelamin = LakiRb.isSelected() ? "Laki-laki" : "Perempuan";

List<String> minat = new ArrayList<>();
for (JCheckBox cb : List.of(JavaCb, PyCb, WebCb)) {
    if (cb.isSelected()) {
        minat.add(cb.getText());
    }
}
String pesan = "Nama: " + NamaField.getText()
+ "\nNPM: " + NpmField.getText()
+ "\nProgram Studi: " + ProgramBox.getSelectedItem()
+ "\nJenis Kelamin: " + jenisKelamin
+ "\nMinat: " + (minat.isEmpty() ? "-" : String.join(", ", minat));

javax.swing.JOptionPane.showMessageDialog(this, pesan, "Data Pendaftaran",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);


}
private void gantiTema(boolean gelap) {
        if (gelap) {
            com.formdev.flatlaf.FlatDarkLaf.setup();
        } else {
            com.formdev.flatlaf.FlatLightLaf.setup();
        }
        com.formdev.flatlaf.FlatLaf.updateUI(); 
        
        // Ubah temaToggle menjadi DarkBt sesuai nama komponenmu
        DarkBt.setText(gelap ? "Mode Terang" : "Mode Gelap"); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       com.formdev.flatlaf.FlatLightLaf.setup();
        // Tampilkan form di Event Dispatch Thread
        java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CeweRb;
    private javax.swing.JButton DaftarBt;
    private javax.swing.JButton DarkBt;
    private javax.swing.JCheckBox JavaCb;
    private javax.swing.ButtonGroup Kelamin;
    private javax.swing.JRadioButton LakiRb;
    private javax.swing.JTextField NamaField;
    private javax.swing.JTextField NpmField;
    private javax.swing.JComboBox<String> ProgramBox;
    private javax.swing.JCheckBox PyCb;
    private javax.swing.JCheckBox WebCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
