/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

/**
 *
 * @author rules
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        ekoRb.setSelected(true);
        setLocationRelativeTo(null); // Biar posisi form di tengah
        
        // Memasang Placeholder sesuai instruksi tugas
        namaField.putClientProperty("JTextField.placeholderText", "Nama sesuai KTP");
        nomorField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");
    }
    private boolean isDarkMode = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        nomorField = new javax.swing.JTextField();
        kotaCb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ekoRb = new javax.swing.JRadioButton();
        ekseRb = new javax.swing.JRadioButton();
        bisnisRb = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        bagasiCb = new javax.swing.JCheckBox();
        makanCb = new javax.swing.JCheckBox();
        asuransiCb = new javax.swing.JCheckBox();
        temaBt = new javax.swing.JButton();
        pesanBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama pesanan");

        jLabel2.setText("Nomor HP");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tiket Travel");

        jLabel4.setText("Kota Tujan");

        kotaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        jLabel5.setText("Kelas");

        buttonGroup1.add(ekoRb);
        ekoRb.setSelected(true);
        ekoRb.setText("Ekonomi");
        ekoRb.addActionListener(this::ekoRbActionPerformed);

        buttonGroup1.add(ekseRb);
        ekseRb.setText("Eksekutif");

        buttonGroup1.add(bisnisRb);
        bisnisRb.setText("Bisnis");

        jLabel6.setText("Fasilitas tambahan");

        bagasiCb.setText("Bagasi");
        bagasiCb.addActionListener(this::bagasiCbActionPerformed);

        makanCb.setText("Makan");
        makanCb.addActionListener(this::makanCbActionPerformed);

        asuransiCb.setText("Asuransi");
        asuransiCb.addActionListener(this::asuransiCbActionPerformed);

        temaBt.setText("Tema Gelap");
        temaBt.addActionListener(this::temaBtActionPerformed);

        pesanBt.setText("Pesan");
        pesanBt.addActionListener(this::pesanBtActionPerformed);

        catatanArea.setColumns(20);
        catatanArea.setRows(5);
        jScrollPane1.setViewportView(catatanArea);

        jLabel7.setText("Catatan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(temaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(236, 236, 236)
                                .addComponent(pesanBt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaField)
                                    .addComponent(nomorField)
                                    .addComponent(kotaCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ekoRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bagasiCb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bisnisRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ekseRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(makanCb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(asuransiCb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(77, 77, 77))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(kotaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekoRb)
                        .addComponent(bisnisRb)
                        .addComponent(ekseRb)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bagasiCb)
                    .addComponent(makanCb)
                    .addComponent(asuransiCb))
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanBt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekoRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekoRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekoRbActionPerformed

    private void bagasiCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagasiCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bagasiCbActionPerformed

    private void makanCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCbActionPerformed

    private void asuransiCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuransiCbActionPerformed

    private void temaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaBtActionPerformed
        // TODO add your handling code here:
        isDarkMode = !isDarkMode; 
        
        if (isDarkMode) {
            com.formdev.flatlaf.FlatDarkLaf.setup();
        } else {
            com.formdev.flatlaf.FlatLightLaf.setup();
        }
        com.formdev.flatlaf.FlatLaf.updateUI(); 
        
        temaBt.setText(isDarkMode ? "Mode Terang" : "Mode Gelap");
    }//GEN-LAST:event_temaBtActionPerformed

    private void pesanBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanBtActionPerformed
        // TODO add your handling code here:
        String kelas = "-";
        if (ekoRb.isSelected()) {
            kelas = "Ekonomi";
        } else if (bisnisRb.isSelected()) {
            kelas = "Bisnis";
        } else if (ekseRb.isSelected()) {
            kelas = "Eksekutif";
        }
        
        // Ambil data Fasilitas (Sesuaikan nama variabel checkbox-mu jika berbeda)
        java.util.List<String> fasilitas = new java.util.ArrayList<>();
        if (bagasiCb.isSelected()) fasilitas.add("Bagasi Ekstra");
        if (makanCb.isSelected()) fasilitas.add("Makan/Minum");
        
        // Buat Ringkasan
        String ringkasan = "--- DATA PEMESANAN TRAVEL ---\n"
                + "Nama: " + namaField.getText() + "\n"
                + "No. HP: " + nomorField.getText() + "\n"
                + "Tujuan: " + kotaCb.getSelectedItem() + "\n"
                + "Kelas: " + kelas + "\n"
                + "Fasilitas Tambahan: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas)) + "\n"
                + "Catatan: " + catatanArea.getText();
                
        // Tampilkan JOptionPane
        javax.swing.JOptionPane.showMessageDialog(this, ringkasan, "Ringkasan Pesanan", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pesanBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCb;
    private javax.swing.JCheckBox bagasiCb;
    private javax.swing.JRadioButton bisnisRb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JRadioButton ekoRb;
    private javax.swing.JRadioButton ekseRb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kotaCb;
    private javax.swing.JCheckBox makanCb;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField nomorField;
    private javax.swing.JButton pesanBt;
    private javax.swing.JButton temaBt;
    // End of variables declaration//GEN-END:variables
}
